AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack for creating an Amazon Image Builder pipeline for golden images.

Parameters:
  PipelineName:
    Type: String
    Default: "Golden Image"
    Description: "Name of the image pipeline."
  PipelineDescription:
    Type: String
    Default: "Mentor task to create golden image that can be used across multiple regions"
    Description: "Description of the image pipeline."
  BuildSchedule:
    Type: String
    Default: "Manual"
    Description: "Build schedule for the pipeline."
  RecipeName:
    Type: String
    Default: "GoldenImage recipe"
    Description: "Name of the recipe."
  RecipeVersion:
    Type: String
    Default: "1.0.0"
    Description: "Version of the recipe."
  RecipeDescription:
    Type: String
    Default: "Golden Image recipe for mentor task"
    Description: "Description of the recipe."
  BaseImageName:
    Type: String
    Default: "arn:aws:imagebuilder:us-east-1:aws:image/ubuntu-server-20-lts-x86/x.x.x"
    Description: "Name of the base image for the recipe."
  WorkingDirectory:
    Type: String
    Default: "/tmp"
    Description: "Working directory for the pipeline."
  DeviceName:
    Type: String
    Default: "/dev/sda1" 
    Description: "Name for the EBS Volume. "
  VolumeType:
    Type: String
    Default: "gp2"
    AllowedValues: ["gp2", "gp3", "io1", "io2", "st1", "sc1"]
    Description: "Type of the EBS volume."
  EncryptionEnabled:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: "Whether encryption should be enabled for the EBS volume."
  VolumeSize:
    Type: String
    Default: "8"
    Description: "Size of the EBS volume in GB."
  InstanceType:
    Type: String
    Default: "t2.micro"
    AllowedValues: ["t2.micro", "t3.micro", "t3a.micro"]
    Description: "EC2 instance type to be used for the image pipeline."


Resources:
  ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Ref RecipeName
      Version: !Ref RecipeVersion
      Description: !Ref RecipeDescription
      ParentImage: !Ref BaseImageName
      Components:
        - ComponentArn: "arn:aws:imagebuilder:us-east-1:aws:component/apache-tomcat-9-linux/1.0.1/1"
        - ComponentArn: "arn:aws:imagebuilder:us-east-1:aws:component/update-linux/1.0.2/1"
      BlockDeviceMappings:
        - DeviceName: !Ref DeviceName
          Ebs:
            VolumeType: !Ref VolumeType
            Encrypted: !Ref EncryptionEnabled 
            DeleteOnTermination: true
            VolumeSize: !Ref VolumeSize

  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: !Sub "${AWS::StackName}-Infrastructure"
      InstanceTypes:
        - !Ref InstanceType
      TerminateInstanceOnFailure: true
      InstanceProfileName: "EC2InstanceProfileForImageBuilder"

  ImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: !Ref PipelineName
      Description: !Ref PipelineDescription
      ImageRecipeArn: !Ref ImageRecipe
      InfrastructureConfigurationArn: !Ref InfrastructureConfiguration
